account_id VARCHAR(16) NOT NULL,

customer_code VARCHAR(16) NOT NULL,
nickname VARCHAR(16) NOT NULL,
pwdkey VARCHAR(256) NOT NULL,
email VARCHAR(64) NOT NULL,
points NUMBER(8, 0) NOT NULL,

CONSTRAINT ACCOUNT_PK
    PRIMARY KEY(account_id),

CONSTRAINT ACCOUNT_CUSTOMER_CODE_FK 
    FOREIGN KEY(customer_code) REFERENCES customer(customer_code)