session_uid NUMBER(16, 0) NOT NULL
    CONSTRAINT MOVIE_SESSION_UID_CK CHECK(session_uid >= 0),

screen_code VARCHAR(16) NOT NULL,
movie_code VARCHAR(16) NOT NULL,
session_datetime TIMESTAMP,
session_round NUMBER(2, 0) DEFAULT 1,

CONSTRAINT MOVIE_SESSION_PK
    PRIMARY KEY(session_uid),

CONSTRAINT MOVIE_SESSION_SCREEN_CODE_FK 
    FOREIGN KEY(screen_code) REFERENCES screen(screen_code),

CONSTRAINT MOVIE_SESSION_MOVIE_CODE_FK
    FOREIGN KEY(movie_code) REFERENCES movie(movie_code)